services:
  # Config Servers (config-server-replset)
  config1:
    image: mongo
    container_name: config1
    command: mongod --config /etc/mongod.yml
    volumes:
      - config1-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/configsvr.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  config2:
    image: mongo
    container_name: config2
    command: mongod --config /etc/mongod.yml
    volumes:
      - config2-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/configsvr.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  config3:
    image: mongo
    container_name: config3
    command: mongod --config /etc/mongod.yml
    volumes:
      - config3-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/configsvr.yml:/etc/mongod.yml
    networks:
      - mongo-cluster

  # Noeud 1 (Shard1)
  shard1-1:
    image: mongo
    container_name: shard1-1
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard1-1-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard1.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard1-2:
    image: mongo
    container_name: shard1-2
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard1-2-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard1.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard1-3:
    image: mongo
    container_name: shard1-3
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard1-3-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard1.yml:/etc/mongod.yml
    networks:
      - mongo-cluster

  # Noeud 2 (Shard2)
  shard2-1:
    image: mongo
    container_name: shard2-1
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard2-1-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard2.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard2-2:
    image: mongo
    container_name: shard2-2
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard2-2-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard2.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard2-3:
    image: mongo
    container_name: shard2-3
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard2-3-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard2.yml:/etc/mongod.yml
    networks:
      - mongo-cluster

  # Noeud 3 (Shard3)
  shard3-1:
    image: mongo
    container_name: shard3-1
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard3-1-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard3.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard3-2:
    image: mongo
    container_name: shard3-2
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard3-2-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard3.yml:/etc/mongod.yml
    networks:
      - mongo-cluster
  shard3-3:
    image: mongo
    container_name: shard3-3
    command: mongod --config /etc/mongod.yml
    volumes:
      - shard3-3-data:/data/db
      - ./keyFile:/data/db/keyFile
      - ./config/shard3.yml:/etc/mongod.yml
    networks:
      - mongo-cluster

  # Mongos router (Config DB)
  mongos:
    image: mongo
    container_name: projet-mongos
    volumes:
      - ./config/mongos.yml:/etc/mongod.yml
      - ./keyFile:/data/db/keyFile
      - mongos-router:/data/db
    depends_on:
      - config1
      - config2
      - config3
    command: mongos --config /etc/mongod.yml
    ports:
      - 27017:27017
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

# volumes:

volumes:
  mongos-router:
  config1-data:
  config2-data:
  config3-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:
  shard3-1-data:
  shard3-2-data:
  shard3-3-data:
