services:
  # Config Servers (config-server-replset)
  config1:
    image: mongo
    container_name: config1
    command: mongod --configsvr --replSet config-server-replset --port 27017
    volumes:
      - ./configsvr/config1:/data/db
    networks:
      - mongo-cluster
  config2:
    image: mongo
    container_name: config2
    command: mongod --configsvr --replSet config-server-replset --port 27017
    volumes:
      - ./configsvr/config2:/data/db
    networks:
      - mongo-cluster
  config3:
    image: mongo
    container_name: config3
    command: mongod --configsvr --replSet config-server-replset --port 27017
    volumes:
      - ./configsvr/config3:/data/db
    networks:
      - mongo-cluster

  # Noeud 1 (Shard1)
  shard1-1:
    image: mongo
    container_name: shard1-1
    command: mongod --shardsvr --replSet shard1 --port 27018
    volumes:
      - ./shard1/shard1-1:/data/db
    networks:
      - mongo-cluster
  shard1-2:
    image: mongo
    container_name: shard1-2
    command: mongod --shardsvr --replSet shard1 --port 27018
    volumes:
      - ./shard1/shard1-2:/data/db
    networks:
      - mongo-cluster
  shard1-3:
    image: mongo
    container_name: shard1-3
    command: mongod --shardsvr --replSet shard1 --port 27018
    volumes:
      - ./shard1/shard1-3:/data/db
    networks:
      - mongo-cluster

  # Noeud 2 (Shard2)
  shard2-1:
    image: mongo
    container_name: shard2-1
    command: mongod --shardsvr --replSet shard2 --port 27018
    volumes:
      - ./shard2/shard2-1:/data/db
    networks:
      - mongo-cluster
  shard2-2:
    image: mongo
    container_name: shard2-2
    command: mongod --shardsvr --replSet shard2 --port 27018
    volumes:
      - ./shard2/shard2-2:/data/db
    networks:
      - mongo-cluster
  shard2-3:
    image: mongo
    container_name: shard2-3
    command: mongod --shardsvr --replSet shard2 --port 27018
    volumes:
      - ./shard2/shard2-3:/data/db
    networks:
      - mongo-cluster

  # Noeud 3 (Shard3)
  shard3-1:
    image: mongo
    container_name: shard3-1
    command: mongod --shardsvr --replSet shard3 --port 27018
    volumes:
      - ./shard3/shard3-1:/data/db
    networks:
      - mongo-cluster
  shard3-2:
    image: mongo
    container_name: shard3-2
    command: mongod --shardsvr --replSet shard3 --port 27018
    volumes:
      - ./shard3/shard3-2:/data/db
    networks:
      - mongo-cluster
  shard3-3:
    image: mongo
    container_name: shard3-3
    command: mongod --shardsvr --replSet shard3 --port 27018
    volumes:
      - ./shard3/shard3-3:/data/db
    networks:
      - mongo-cluster

  # Mongos router (Config DB)
  mongos:
    image: mongo
    container_name: projet-mongos
    depends_on:
      - config1
      - config2
      - config3
    command: >
      mongos --configdb config-server-replset/config1:27017,config2:27017,config3:27017 --port 27017
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
