storage:
  dbPath: /data/db

net:
  bindIp: 0.0.0.0
  port: 27018

replication:
  replSetName: shard2
sharding:
  clusterRole: shardsvr


# Active Auth


security:
  authorization: "enabled"
  keyFile: data/db/keyFile


