storage:
  dbPath: /data/db

net:
  bindIp: 0.0.0.0
  port: 27018

replication:
  replSetName: shard1

sharding:
  clusterRole: shardsvr

security:
  authorization: "enabled"
  keyFile: data/db/keyFile
